# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: temporal/api/errordetails/v1/message.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class NotFoundFailure(betterproto.Message):
    current_cluster: str = betterproto.string_field(1)
    active_cluster: str = betterproto.string_field(2)


@dataclass
class WorkflowExecutionAlreadyStartedFailure(betterproto.Message):
    start_request_id: str = betterproto.string_field(1)
    run_id: str = betterproto.string_field(2)


@dataclass
class NamespaceNotActiveFailure(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    current_cluster: str = betterproto.string_field(2)
    active_cluster: str = betterproto.string_field(3)


@dataclass
class RetryTaskFailure(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workflow_id: str = betterproto.string_field(2)
    run_id: str = betterproto.string_field(3)
    next_event_id: int = betterproto.int64_field(4)


@dataclass
class RetryTaskV2Failure(betterproto.Message):
    namespace_id: str = betterproto.string_field(1)
    workflow_id: str = betterproto.string_field(2)
    run_id: str = betterproto.string_field(3)
    start_event_id: int = betterproto.int64_field(4)
    start_event_version: int = betterproto.int64_field(5)
    end_event_id: int = betterproto.int64_field(6)
    end_event_version: int = betterproto.int64_field(7)


@dataclass
class ClientVersionNotSupportedFailure(betterproto.Message):
    client_version: str = betterproto.string_field(1)
    client_impl: str = betterproto.string_field(2)
    supported_versions: str = betterproto.string_field(3)


@dataclass
class FeatureVersionNotSupportedFailure(betterproto.Message):
    feature: str = betterproto.string_field(1)
    feature_version: str = betterproto.string_field(2)
    supported_versions: str = betterproto.string_field(3)


@dataclass
class CurrentBranchChangedFailure(betterproto.Message):
    current_branch_token: bytes = betterproto.bytes_field(1)


@dataclass
class ShardOwnershipLostFailure(betterproto.Message):
    owner: str = betterproto.string_field(1)


@dataclass
class NamespaceAlreadyExistsFailure(betterproto.Message):
    pass


@dataclass
class CancellationAlreadyRequestedFailure(betterproto.Message):
    pass


@dataclass
class QueryFailedFailure(betterproto.Message):
    pass


@dataclass
class EventAlreadyStartedFailure(betterproto.Message):
    pass
